{% set name = "txl-markdown-viewer" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_markdown_viewer-{{ version }}.tar.gz
  sha256: b5ee49a406f4cac61ac5332f2c5005a3208793e5687da203d2d45f0398d6b931

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl >=0.2.18,<0.3.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_markdown_viewer

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/markdown_viewer
  summary: TXL plugin for a Markdown viewer
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/markdown_viewer
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
