{% set python_min = "3.10" %}
{% set name = "txl-markdown-viewer" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_markdown_viewer-{{ version }}.tar.gz
  sha256: 500400abc90da550075eba0b51a22574e39e624a25799cf778dbaedd6b9864e4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl =0.3.2

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - txl_markdown_viewer

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/markdown_viewer
  summary: TXL plugin for a Markdown viewer
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/markdown_viewer
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
